### ISSUE TITLE
Registration configuration resets on every page load

### ISSUE THREAD

**Issue by mattiasgeniar** [facebook/fbctf#567] opened 2017-09-06 11:04 UTC
Please include the following information when filing an issue 
• Current version of FBCTF installed: 1f236bba7e5e7a3e7169ff61037502a6928a94ba
• System and Installation details: Ubuntu 14.04
• Detailed description of the problem

Whenever the configuration is updated, the database updates accordingly;

```
mysql> select * from configuration where field like '%registration%';
+----+----------------------+-------+----------------------------------------------------------+
| id | field                | value | description                                              |
+----+----------------------+-------+----------------------------------------------------------+
| 16 | registration         | 1     | (Boolean) Ability to register teams                      |
```

The value = 1 is what is expected.

However, every page refresh that follows, the configuration is reset. This is noted mostly on the "registration" field that keeps resetting to 0.

```
mysql> select * from configuration where field like '%registration%';
+----+----------------------+-------+----------------------------------------------------------+
| id | field                | value | description                                              |
+----+----------------------+-------+----------------------------------------------------------+
| 16 | registration         | 0     | (Boolean) Ability to register teams                      |
```

That value keeps resetting to 0, no matter what value is configured in the GUI.

No errors are logged. I'm a bit at loss at where to look to further troubleshoot this.

**Comment by stevcoll** [comment] 2017-09-09 17:37
@mattiasgeniar Very strange issue. Some questions to clarify:

1. Which provision mode did you use? (dev/prod/multi-server/docker/vagrant)
2. Do you have the full provision command you ran still handy?
3. When you say "page referesh" are you literally refreshing the admin page? Or browsing to other pages then going back and seeing the value reset.
4. Is memcached running on your system? (ps aux | grep memcached)
5. Have you made any code changes to the platform or any database changes directly?
6. Is this happening while the game is started, or is it pre-game?

**Comment by denoli** [comment] 2017-09-15 14:55
@stevcoll Thanks for your reply! To clarify:

1. Prod
2. $ ./extra/provision.sh -m prod -s $PWD -D ctf.example.com -e olivier@example.com -d /var/www/ctf.example.com/docs
3. Both on refresh & when comming back to the page
4. yes, memcached is running: /usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1
5. No
6. While the game is started
7. 
[Wed Sep  6 10:56:00 2017] [hphp] [3709:7f35633ff700:27:000001] [] #0 /var/www/ctf.example.com/docssrc/Router.php(71): SessionUtils::enforceLogin()\n#1 /var/www/ctf.example.com/docssrc/Router.php(20): Router::genRouteNormal()\n#2 /var/www/ctf.example.com/docssrc/index.php(7): Router::genRoute()\n#3 (): genInit()\n#4 /var/www/ctf.example.com/docssrc/index.php(17): HH\\Asio\\join()\n#5 {main}

**Comment by stevcoll** [comment] 2017-09-15 21:39
@mattiasgeniar I ran through your scenario and was not able to duplicate this issue. The options are persisting during a game as well.

The only thing I can think of based on your error, is that your admin session timed out. If that happened on the admin page, the options would not take effect. However, upon a hard page refresh or going to another page, you would be sent back to the home screen and forced to login.

Is there anything happening in the MySQL logs (errors etc?) You could also try turning on the MySQL General Query log and see what is happening to reset these values, and when that is happening.

**Comment by stevcoll** [comment] 2017-09-26 04:41
Closing since this cannot be reproduced at this point in time. Please let us know if you have further issues.

**Closed by stevcoll** 2017-09-26 04:41 UTC
