### ISSUE TITLE
Deleting a user leads to unusable admin area

### ISSUE THREAD

**Issue by paulmar** [facebook/fbctf#111] opened 2016-05-26 21:59 UTC
After deleting a regular user through the admin area, parts of the admin become unusable.

Accessing the Configuration section does not work:
`[Thu May 26 21:56:56 2016] [hphp] [10216:7f418afff700:715:000001] [] \nFatal error: Uncaught exception 'HH\\InvariantException' with message 'Expected exactly one result' in /var/www/fbctf/src/models/Session.php:94\nStack trace:\n#0 /var/www/fbctf/src/models/Session.php(94): HH\\invariant_violation()\n#1 (): Session::gen()\n#2 (): HH\\WaitHandle->join()\n#3 /var/www/fbctf/src/SessionUtils.php(59): HH\\Asio\\join()\n#4 (): SessionUtils::read()\n#5 (): call_user_func()\n#6 /var/www/fbctf/src/SessionUtils.php(32): __SystemLib\\SessionForwardingHandler->read()\n#7 /var/www/fbctf/src/inc/gameboard/modules/leaderboard.php(6): SessionUtils::sessionStart()\n#8 {main}`

Ending the game does not work:
`Thu May 26 21:53:51 2016] [hphp] [10216:7f41747ff700:534:000001] [] \nFatal error: Uncaught exception 'OutOfBoundsException' with message 'Integer key 0 is out of bounds' in /var/www/fbctf/src/models/Control.php:37\nStack trace:\n#0 /var/www/fbctf/src/models/Level.php(827): Control::genScriptPid()\n#1 /var/www/fbctf/src/models/Control.php(109): Level::genStopBaseScoring()\n#2 /var/www/fbctf/src/controllers/ajax/AdminAjaxController.php(441): Control::genEnd()\n#3 /var/www/fbctf/src/controllers/ajax/AjaxController.php(14): AdminAjaxController->genHandleAction()\n#4 /var/www/fbctf/src/Router.php(57): AjaxController->genHandleRequest()\n#5 /var/www/fbctf/src/Router.php(13): Router::genRouteAjax()\n#6 /var/www/fbctf/src/index.php(7): Router::genRoute()\n#7 (): genInit()\n#8 (): HH\\WaitHandle->join()\n#9 /var/www/fbctf/src/index.php(19): HH\\Asio\\join()\n#10 {main}`

**Comment by javuto** [comment] 2016-05-27 00:38
This seems like a problem. Is this in the middle of a game? Are there scores done by that team?

**Comment by paulmar** [comment] 2016-05-27 09:06
Yes, it was in the middle of the game and I believe some teams had points. I can take another look if you can't reproduce.

**Comment by wotd** [comment] 2016-06-02 14:49
@javuto any ideas how to fix it? Same problem here...

**Comment by wotd** [comment] 2016-06-03 08:26
@paulmar and @javuto  - I have executed this query in mysql: 
mysql> delete from progressive_log;
Query OK, 470 rows affected (0.01 sec)
and now admin panel is back. I hope it will help you find the issue

**Comment by mjksec** [comment] 2016-06-03 21:54
I had the same problem after deleting a team after they accidentally created a wrong team. Now am unable to access admin panel.

What are the steps exactly to remove?

**Comment by wotd** [comment] 2016-06-04 05:43
@mjksec ssh to server, run mysql -uctf -p (default password is: ctf). in mysql change database to fbctf: **use fbctf;** and then this command: **delete from progressive_log;** I was comparing two instances (one with no access to admin after team deletion and second one, fresh installed) and I was trying to remove entries that were not present in second one (of course I skipped already created puzzles). My instance was usable again after I cleared progressive_log table.

**Comment by mjksec** [comment] 2016-06-04 17:00
Thanks @wotd.

I tried that, and the output was as above "Query OK."

But it doesn't get me back to the admin page. Logging in, I get an 

ctf is currently unable to handle this request.
HTTP ERROR 500

If I run status on the db. I get the following output

`status;
--------------
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

Connection id:		67
Current database:	
Current user:		ctf@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.5.49-0ubuntu0.14.04.1 (Ubuntu)
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	latin1
Db     characterset:	latin1
Client characterset:	latin1
Conn.  characterset:	latin1
UNIX socket:		/var/run/mysqld/mysqld.sock
Uptime:			19 hours 12 min 37 sec

Threads: 2  Questions: 402  Slow queries: 0  Opens: 71  Flush tables: 1  Open tables: 61  Queries per second avg: 0.005`

Any ideas?

**Comment by wotd** [comment] 2016-06-04 18:20
Sorry @mjksec it just worked for me. Maybe try restart services - hhvm, nginx and mysql?

**Comment by mjksec** [comment] 2016-06-04 21:37
Nope, didn't work either. 
I also tried force-reload on HHVM and NGINX.

What has worked for me though, is specifying a URL path beyond the admin login.

For example - https://domain/index.php?p=admin&page=logs

It's a crappy workaround at present until I work out how to fix it. But I have a game scheduled for Monday with my team to present this as an awareness platform, so I was beginning to panic a bit.

**Comment by boyokmard** [comment] 2016-06-05 07:45
Same issue here. @wotd workaround didn't work. Any idea how to fix this issue?  @mjksec

**Comment by boyokmard** [comment] 2016-06-05 08:36
OK, I figure out a workaround. The issue is with foreign key (team_id) in registration_tokens table. Execute 'delete from registration_tokens' to delete all tokens and you are good to go.

**Comment by wotd** [comment] 2016-06-05 09:40
Right! I did it too! However I am pretty sure I checked after this and I had still blank panel - maybe browser cache? Anyway, good there finally is working workaround:) thx @boyokmard

**Comment by mjksec** [comment] 2016-06-05 10:08
Brilliant! Confirm that worked.

**Comment by rdenman** [comment] 2016-09-07 20:58
Check out #206 for a more permanent solution. Creating a MySQL trigger to delete some other team-related information in the database fixes the issue. I'll try to get around to creating a PR when I get a chance.

**Comment by justinwray** [comment] 2016-11-28 10:33
This issue should be resolved in PR #372.

**Closed** 2016-12-14 10:13 UTC
Labels: bug, platform
