### ISSUE TITLE
Challenge bonus points dont get reset on new games

### ISSUE THREAD

**Issue by swappage** [facebook/fbctf#123] opened 2016-06-04 23:12 UTC
This can be trivial, considering that generally you run the same game once.

but i think this is important as i generally test the platform and the challenges before going to production.

I noticed that when you start the first fresh game, points are scored accordingly:
- first solve BASE+30
- second solve BASE+20
- third solve BASE + 10

if you stop the game and start a new one from scratch with the same challenges bonus points counter is not reset

- first solve: BASE

if a fix is not to be issued, can someone help me out in figuroing out how to reset the points?

**Comment by gsingh93** [comment] 2016-06-04 23:29
Duplicate of #82. Easiest way to reset points until this bug is fixed is to run a SQL `UPDATE` command on the levels table, setting the bonus value to what you want.

**Closed by gsingh93** 2016-06-04 23:29 UTC
